deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TravisCl
  keep_history: true
  on:
    branch: master
language: python
python:
  - 3.6
install:
  - pip install python-coveralls
script: 
  - python test_simple_calculator.py
  - coverage run test_simple_calculator.py
after_success:
  - coveralls
