deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TravisCl
  keep_history: true
  on:
    branch: master
install:
  $ pip install python-coveralls
language: python
python:
  - 3.6
script: python TestSimpleCalculator.py
after_success:
  - coveralls
