deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TravisCl
  keep_history: true
  on:
    branch: master
language: python
python:
  - 3.6
script: 
  - python TestSimpleCalculator.py
  - coverage run --source=home TestSimpleCalculator.py
after_success:
  - coveralls
